### ISSUE TITLE
Newer Posts / Older Posts Links

### ISSUE THREAD

**Issue by natnotes** [mich8060/_kindred#7]
Is this how you expected it to look? 
<img width="417" alt="screenshot 2017-10-28 15 21 47" src="https://user-images.githubusercontent.com/8162670/32138668-f7690d26-bbf3-11e7-936e-ac8fc4d4c2dd.png">
<img width="293" alt="screenshot 2017-10-28 15 21 59" src="https://user-images.githubusercontent.com/8162670/32138669-f780e054-bbf3-11e7-8161-02bd7cb8abb0.png">

I'm on this page: 
https://thekindredconversation.com/category/new-adages/page/2/

**Comment by mich8060** [comment]
Should be fixed now, closing ticket.
