### ISSUE TITLE
Edit mode when logged into WP-ADMIN

### ISSUE THREAD

**Issue by natnotes** [mich8060/_kindred#9]
Doesn't seem like edit more when logged into WP-ADMIN console is working.

**Comment by mich8060** [comment]
Do you mean the little bar at the top?

**Comment by natnotes** [comment]
The little "Edit Pencil" icon - so you can edit a page that you're viewing
on prod when you're logged into admin.

**Comment by mich8060** [comment]
Fixed locally. Include in next push.

**Comment by mich8060** [comment]
Editing mode added to the following pages:
Generic Pages
Podcasts
Articles
Relationships
Dating
Adages

**Comment by mich8060** [comment]
Pushed: Nov. 15, 2017
